### ISSUE TITLE
local compilation is not incremental

### ISSUE THREAD

**Issue by rusefillc** [rusefi/fw-custom-example#15]
under WSL

```
git clone --recurse-submodules https://github.com/rusefi/fw-custom-example
```

```



cd /home/rusefi/fw-custom-example
./compile_firmware.sh
./compile_firmware.sh
```

expected: second compilation does not really compile everything
actual result: second compilation compiles everything :(

**Comment by rusefillc** [comment]
@chuckwagoncomputing any chance you could help with diagnostics of root causes of the issue, if the issue reproduces for you with latest of this repo?

FYI recent progress https://github.com/rusefi/fw-custom-example/issues/14 https://github.com/rusefi/rusefi/issues/6879 was to generate much more of files not into submodule folders but into local generated https://github.com/rusefi/fw-custom-example/commit/e42639db7459e98588491d0315b945d459304e58

While this gave clarity of what is changed - at least all headers are now local to this custom repo - it did not help with incremental compilation like I was hoping it would

**Comment by esaulenka** [comment]
looks like `make` always tries recompile everyting due to recreation of these auto-generated files
```
     Prerequisite '../../../connectors/generated_outputs.h' is newer than target 'pch/pch.h.gch/firmware'.
     Prerequisite '../../../connectors/generated_ts_name_by_pin.cpp' is newer than target 'pch/pch.h.gch/firmware'.
```
and next, for these files
```
     Prerequisite '.config-sentinel' is newer than target '../../../connectors/generated_outputs.h'.
     Prerequisite '.docsenums-sentinel' is older than target '../../../connectors/generated_outputs.h'.
    Must remake target '../../../connectors/generated_outputs.h'.
```

and... what is it?! what is the 'signature_XYZ' ?
```
       Finished prerequisites of target file '.config-sentinel'.
       Prerequisite '../../../generated/tunerstudio/generated/signature_XYZ.txt' of target '.config-sentinel' does not exist.
       Prerequisite 'controllers/algo/rusefi_hw_stm32_enums.h' is older than target '.config-sentinel'.
       Prerequisite 'controllers/algo/rusefi_hw_adc_enums.h' is older than target '.config-sentinel'.
...
       Prerequisite '.target-sentinel' is older than target '.config-sentinel'.
      Must remake target '.config-sentinel'.
```

**Comment by rusefillc** [comment]
```
--- a/firmware/bin/compile.sh
+++ b/firmware/bin/compile.sh

-make $B -j$(nproc) -r $MAKE_ARGS
+# make $B -j$(nproc) -r $MAKE_ARGS
+make -d $B -r $MAKE_ARGS
```

**Comment by rusefillc** [comment]
Looks fixed thank you @esaulenka

**Comment by esaulenka** [comment]
> make -d $B -r $MAKE_ARGS

to clarify: this one can be used to debugging Makefiles.
It produses huge logs (~15MB in this case), but you can find there the whole sequence, which file depends on which one.
