### ISSUE TITLE
Calling files _XXX makes stupid Windows Defender think it has a virus

### ISSUE THREAD

**Issue by ElDominio** [rusefi/fw-custom-example#6]
microsoft is dumb

**Comment by rusefillc** [comment]
@ElDominio what are you talking about? what files? why do we care?

I am not facing any issues on win 7, 10 and 11

**Comment by ElDominio** [comment]
i downloaded this file
![image](https://github.com/rusefi/fw-custom-example/assets/5685108/24c86d98-76c5-4bcc-8e0f-f4c83bc64a44)

it downloaded a zip that has a zip inside it (why?)
![image](https://github.com/rusefi/fw-custom-example/assets/5685108/8654c467-fe8f-4303-8843-5dd92de65857)

extracted it
![image](https://github.com/rusefi/fw-custom-example/assets/5685108/15dab24e-3a4a-450b-87e8-4a85a8320085)

trying to open it made this happen
![image](https://github.com/rusefi/fw-custom-example/assets/5685108/7f74aff5-5e57-4317-af52-6536339cb8ac)
the file was then deleted by windows on its own

I was only successful doing double unzip with 7zip

**Comment by chuckwagoncomputing** [comment]
What happens if you disable Defender, unzip it, then re-enable Defender? Do any files get deleted in the unzipped folder? If so, which?

**Comment by ElDominio** [comment]
> What happens if you disable Defender, unzip it, then re-enable Defender? Do any files get deleted in the unzipped folder? If so, which?

Once I unzip the first zip, the second zip shows. If i try to unzip that; it gets deleted even if "real-time protection" is not running in Windows Defender
