### ISSUE TITLE
Can I have an example of how to name a pin? And how to make said named pin a default pin in the base tune?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/fw-custom-example#7]
I would like to call for example, PA6 -> "CKP"

And then, I'd like the Crank Sensor (Primary Channel) to show "CKP" instead of "NONE"

if possible

**Comment by rusefillc** [comment]
@ElDominio default configuration is now documented at https://github.com/rusefi/rusefi/wiki/Custom-Firmware#default-board-configuration
